name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo scripts/install_dependencies.sh
    - name: setup
      run: autoreconf -if
    - name: configure
      run: ./configure --enable-posix --disable-analogy
    - name: make
      run: make
    - name: make check
      run: make check
    - name: report problems
      run: cat tests/test-suite.log
      if: ${{ failure() }}
