name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: scripts/install_dependencies.sh
    - name: setup
      run: autoreconf -if
    - name: configure
      run: ./configure --enable-posix --disable-analogy
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
